version: "3"
services:
    app:
        container_name: app
        build: .
        tty: true
        volumes:
            - ./app:/go/src/app
    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: sample-mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=sample_db
        command: >
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_general_ci
          --innodb_file_per_table
          --innodb_file_format=BARRACUDA
          --innodb_large_prefix=1
        ports:
          - 3306:3306
        depends_on:
          - app